format = "$directory$character"
palette = "catppuccin_macchiato"
right_format = "$git_branch"
[character]
error_symbol = "[ ](rosewater)"
success_symbol = "[ ](red)"
vimcmd_symbol = "[ ](green)"

[directory]
style = "bold pink"
truncation_length = 1

[git_branch]
format = "[ $symbol$branch]($style) "
style = " rosewater"
symbol = "󱐚 "
ignore_branches = ['main']
truncation_length = 10
truncation_symbol = ""

[palettes.catppuccin_macchiato]
flamingo = "#f0c6c6"
maroon = "#ee99a0"
mauve = "#c6a0f6"
peach = "#f5a97f"
pink = "#f5bde6"
red = "#ed8796"
rosewater = "#f4dbd6"

