theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
color-modes = true
completion-trigger-len=1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
 

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
display-messages = true
snippets = true

[keys.normal]
C-q = ":q"
C-s = ":w"
A-x = ":bc"
A-s = ":wq"

A-g = "yank"

[keys.insert]
A-k = "move_line_up"
A-j = "move_line_down"
C-c = "normal_mode"
A-i = "goto_line_start"
C-a = "kill_to_line_end"
A-c = "move_prev_word_end"
C-i = "kill_to_line_start"
A-l = "delete_word_backward"
C-l = "delete_char_backward"
A-a = "goto_line_end_newline"
'j' = {k='normal_mode','j'={'k'=[':insert-output /bin/echo -n j','move_char_right','normal_mode']}}


