name: Check flake configuration

on:
  push:
    branches:
      - macOS

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
       
      - name: Install Nix package manager
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check flake
        run: |
          nix flake check
          nix flake show
